name: Hello Marce

on:
  push:
    branches:
      - main # might be `master` for older repos
  repository_dispatch:
    types: [trigger_deploy]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: echo "Hello Marce"
